stages:
  - check
  - build
  - test
  - push
  - trigger
  - docs

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS == null
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG

# Not making these global variables because they would get overridden in multi-project pipelines
.variables: &variables
  # The base of this repo's docker registry
  REPO_DOCKER_REGISTRY: ${CI_REGISTRY_IMAGE}
  # The image name of binaryninja-haskell image
  BLAZE_BINARYNINJA_HASKELL_IMAGE:
    ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/binaryninja-haskell/binaryninja-haskell
  # Enable buildkit for more efficient layer caching
  DOCKER_BUILDKIT: "1"

# Potential build dependencies for the dind host
.script-bootstrap-dind: &script-bootstrap-dind
  - echo -e "section_start:`date +%s`:bootstrap[collapsed=true]\r\e[0KBootstrap build dependencies"
  - |
    if [ -f /etc/alpine-release ]; then
      apk add git coreutils python3
      apk add -X http://dl-cdn.alpinelinux.org/alpine/edge/testing time
    fi
  - echo -e "section_end:`date +%s`:bootstrap\r\e[0K"

.job:
  timeout: 1h
  variables:
    <<: *variables
  before_script: &job-before-script
    - echo -e "section_start:`date +%s`:pre-env[collapsed=true]\r\e[0KEnvironment info (before_script)"
    - uname -a
    - env
    - ls -al
    - find . -maxdepth 1 \( ! -name . \) -print0 | sort -z | xargs -0 -x du -bhsc
    - df -h
    - date -Iseconds
    - |
      if type git >/dev/null; then
        pushd "$BLAZE_BINJA_API" >/dev/null && \
          { git log --color --decorate HEAD^..HEAD | cat || true;
            popd >/dev/null;
          } || true
      fi
    - |
      if type python3 >/dev/null; then
        python3 -c 'import binaryninja; print(binaryninja.core_version())' || true
      fi
    - echo -e "section_end:`date +%s`:pre-env\r\e[0K"

.docker-job:
  extends: .job
  image: docker:dind
  before_script:
    - *script-bootstrap-dind
    - *job-before-script
    - docker login -u "${CI_REGISTRY_USER}" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"

.haskell-job:
  extends: .job
  image: ${REPO_DOCKER_REGISTRY}/blaze:pipeline-${CI_PIPELINE_IID}

# stage: check
include:
  project: 'kevino/filter-check'
  file: '/filtercheck.gitlab-ci.yml'

lint:
  stage: check
  extends: .job
  image: ${BLAZE_BINARYNINJA_HASKELL_IMAGE}
  needs: []
  script:
    - hlint --color=always src test demo
  allow_failure: true

build:
  stage: build
  extends: .docker-job
  needs: []
  script:
    - image=${REPO_DOCKER_REGISTRY}/blaze
    - docker pull "${image}:latest" || true
    - if [ "${CI_COMMIT_BRANCH}" = "${CI_DEFAULT_BRANCH}" ]; then
        build_type=release;
      else
        build_type=dev;
      fi
    - docker build --pull . -f Dockerfile
      --build-arg "CI_REGISTRY=${CI_REGISTRY}"
      --build-arg "CI_PROJECT_NAMESPACE=${CI_PROJECT_NAMESPACE}"
      --build-arg "BUILD_TYPE=${build_type}"
      --build-arg STACK_BUILD_OPTIONS=--ghc-options=-fdiagnostics-color=always
      -t "${image}:pipeline-${CI_PIPELINE_IID}"
    - docker push "${image}:pipeline-${CI_PIPELINE_IID}"

test-general:
  stage: test
  extends: .haskell-job
  needs:
    - build
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - cd /blaze/build/blaze
    - .ci/scripts/run_test.py ~/.local/bin/blaze-general-test

test-binja:
  stage: test
  extends: .haskell-job
  needs:
    - build
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - cp -T "${BLAZE_BINJA_LICENSE_FILE}" /root/.binaryninja/license.dat
    - cd /blaze/build/blaze
    - .ci/scripts/run_test.py ~/.local/bin/blaze-binja-test

test-ghidra:
  stage: test
  extends: .haskell-job
  needs:
    - build
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - cd /blaze/build/blaze
    - .ci/scripts/run_test.py ~/.local/bin/blaze-ghidra-test

push:latest:
  stage: push
  extends: .docker-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - test-general
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - image=${REPO_DOCKER_REGISTRY}/blaze
    - docker pull "${image}:pipeline-${CI_PIPELINE_IID}"
    - docker tag "${image}:pipeline-${CI_PIPELINE_IID}" "${image}:latest"
    - docker push "${image}:latest"

push:tag:
  stage: push
  extends: .docker-job
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - test-general
  variables:
    <<: *variables
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  script:
    - image=${REPO_DOCKER_REGISTRY}/blaze
    - docker pull "${image}:pipeline-${CI_PIPELINE_IID}"
    - docker tag "${image}:pipeline-${CI_PIPELINE_IID}" "${image}:tag-${CI_COMMIT_TAG}"
    - docker push "${image}:tag-${CI_COMMIT_TAG}"

pages:
  extends: .docker-job
  stage: docs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_MERGE_REQUEST_ID == null
      when: on_success
    - if: $CI_MERGE_REQUEST_ID == null
      when: manual
  needs:
    - test-general
  variables:
    <<: *variables
  script:
    - image=${REPO_DOCKER_REGISTRY}/blaze
    - docker build --pull .
      --build-arg "CI_REGISTRY=${CI_REGISTRY}"
      --build-arg "CI_PROJECT_NAMESPACE=${CI_PROJECT_NAMESPACE}"
      --target docs
      -t "${image}/docs:pipeline-${CI_PIPELINE_IID}"
    - mkdir public
    - docker run --rm -v $PWD/public:/public "${image}/docs:pipeline-${CI_PIPELINE_IID}" tar -cvC docs . | tar -xvC public --no-same-owner
  allow_failure: true
  artifacts:
    paths:
      - public
    expire_in: 12 hours

cleanup:
  stage: .post
  when: always
  extends: .docker-job
  variables:
    GIT_STRATEGY: none
  script:
    - apk add --no-cache --update bash
    - "# Untag all images created by this pipeline so we don't waste space on CI runner"
    - |
      bash -c '
        images=(${REPO_DOCKER_REGISTRY}/blaze)
        tags=()
        for image in "${images[@]}"; do
          tags+=(
            "${image}:pipeline-${CI_PIPELINE_IID}"
            "${CI_COMMIT_TAG:+${image}:tag-${CI_COMMIT_TAG}}"
            )
        done
        for i in "${!tags[@]}"; do if [ -z "${tags[$i]}" ]; then unset tags[$i]; fi; done
        echo "${tags[@]}"
        docker image rm "${tags[@]}" || true
      '
