version: "3.4"

services:
  flint:
    image: ${DOCKER_REGISTRY:+${DOCKER_REGISTRY}/}blaze/blaze-platform
    entrypoint: ["/out/bin/flint"]
    command: ["--help"]
    build:
      context: .
      platforms:
        - linux/amd64
    volumes:
      - ${BLAZE_BINARYNINJA_LICENSE_FILE:-./license.dat}:/root/.binaryninja/license.dat:ro
