name:                flint
version:             0.1.0.0
license:             BSD-2-Clause
author:
  - Matt (drone) Revelle <drone@bitrit.es>
  - Matt Parker <mp@kududyn.com>
  - Kevin Orr <kevino@kududyn.com>
maintainer:
  - Matt Parker <mp@kududyn.com>
  - Kevin Orr <kevino@kududyn.com>
  - Matt (drone) Revelle <drone@bitrit.es>
copyright:           "2023 Kudu Dynamics"
synopsis:            An analysis tool that aids in finding bugs.
category:            Program Analysis, Binary Analysis
description:         Please see the README.

extra-source-files:
- README.md
- ChangeLog.md


dependencies:
  - aeson
  - algebraic-graphs ==0.6.1
  - async
  - base >=4.7 && <5
  - bimap
  - blaze
  - bv
  - bytestring
  - casing
  - constraints
  - containers
  - data-binary-ieee754
  - directory
  - dlist
  - envy
  - extra
  - generic-lens
  - generics-sop
  - ghidra
  - hashable
  - lens
  - list-t
  - megaparsec
  - mtl
  - newtype
  - parser-combinators
  - pretty-simple
  - random
  - raw-strings-qq
  - recursion-schemes
  - relude
  - sbv >=8.6 && <10
  - stm
  - streamly
  - string-conversions
  - template-haskell
  - text
  - time
  - transformers
  - unordered-containers
  - uuid >=1.3.14
  - vector

language: GHC2021

default-extensions:
  - AllowAmbiguousTypes
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - DuplicateRecordFields
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedLabels
  - OverloadedStrings
  - TypeFamilies
  - ViewPatterns

library:
  ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wpartial-fields
  - -Wmissing-home-modules
  - -j4
  - -O2
  source-dirs:
  - src
  exposed-modules:
  - Flint.Prelude
  - Flint.Analysis.Uefi
  - Flint.Analysis
  - Flint.Analysis.Path.Matcher
  - Flint.Types.Analysis
  - Flint.Util
  - Flint.Cfg
  - Flint.Cfg.Path
  - Flint.Cfg.Store
  - Flint.Types.Cfg.Store
  - Flint.Types.CachedCalc
  - Flint.Types.Query
    
include-dirs:
  - "src"
  - "../binaryninja-haskell/res"

executables:
  flint:
    main: Main.hs
    source-dirs:  app
    ghc-options:
    - -j4
    - -O2
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint
  ev1smm:
    main: Main.hs
    source-dirs: demo/ev1smm
    ghc-options:
    - -j4
    - -O2
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint
  kernel:
    main: Main.hs
    source-dirs: demo/Kernel
    ghc-options:
    - -j4
    - -O2
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint
  demo1-demo:
    main: Main.hs
    source-dirs: demo/Demo1
    ghc-options:
    - -j4
    - -O2
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint

    
tests:
  flint-tests:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -j4
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint
    - hspec
