name:                haze
version:             0.1.0.0
github:              "mp/haze"
license:             BSD3
author:              "Matt Parker"
maintainer:          "mp@kududyn.com"
copyright:           "2019 Kudu Dynamics"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the readme

dependencies:
  - attoparsec
  - base >= 4.7 && < 5
  - casing
  - containers
  - data-binary-ieee754
  - envy
  - hinja
  - lens
  - mtl
  - newtype
  - pretty-simple
  - protolude
  - raw-strings-qq
  - stm
  - template-haskell
  - text
  - transformers

default-extensions:
  - OverloadedStrings
  - FlexibleInstances
  - FlexibleContexts
  - TupleSections
  - NoImplicitPrelude   
  - ScopedTypeVariables
  - GeneralizedNewtypeDeriving
  - DeriveGeneric
  - DeriveDataTypeable
  - LambdaCase
  - DuplicateRecordFields
  - MultiParamTypeClasses
  - FunctionalDependencies
  - StandaloneDeriving
  - GADTs
  
library:
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -j
  - +RTS
  - -s
  - -A256m
  - -n16m
  - -RTS
  source-dirs: src
  exposed-modules:
  - Haze.Prelude

include-dirs:
  - "src"

# tests:
#   haze-test:
#     main: Spec.hs
#     source-dirs:
#     - test
#     ghc-options:
#     - -Wall
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - containers
#     - haze
#     - hspec
#     - text
