name:                ghidra
version:             0.1.0
license:             BSD-2-Clause
author:
  - Matt (drone) Revelle <drone@kududyn.com>
  - Matt Parker <mp@kududyn.com>
  - Kevin Orr <kevino@kududyn.com>
maintainer:          
  - Matt (drone) Revelle <drone@kududyn.com>
  - Matt Parker <mp@kududyn.com>
  - Kevin Orr <kevino@kududyn.com>
copyright:           "2022 Kudu Dynamics"
synopsis:            Call Clojure from Haskell
category:            Bindings
description:         Please see the README.

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
  - async
  - base
  - binary-analysis
  - bytestring
  - containers
  - directory
  - envy
  - errors
  - extra
  - generic-lens
  - io-memoize
  - jni
  - jvm
  - lens
  - mtl
  - newtype
  - pretty-simple
  - protolude
  - random
  - singletons-base
  - stm
  - string-conversions
  - template-haskell >= 2.18.0.0
  - text
  - transformers
  - unordered-containers
  - vector

default-extensions:
  - BangPatterns
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedStrings
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections


library:
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -j4
  - -O2
  extra-libraries: jvm
  source-dirs:
    - src
    - res/c
    - res/bridge
  c-sources:
    - res/c/java.c
    - res/bridge/ffijni.c
  exposed-modules:
    - Ghidra.Address
    - Ghidra.Core
    - Ghidra.Function
    - Ghidra.Instruction
    - Ghidra.Pcode
    - Ghidra.Prelude
    - Ghidra.Program
    - Ghidra.Reference
    - Ghidra.State
    - Ghidra.Types.Address
    - Ghidra.Types.Pcode
    - Ghidra.Types.Variable
    - Language.Clojure
    - Language.Clojure.Core
    - Language.Clojure.Map


include-dirs:
  - "src"
  - "res"
  - "res/bridge"
  - "/usr/lib/jvm/java-11-openjdk-amd64/include"

tests:
  ghidra-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -j4
    - -O2
    extra-libraries: jvm
    dependencies:
    - containers
    - ghidra
    - hspec
    - text
