resolver: lts-24.33
# Always keep `compiler` explicit because it's used by the Dockerfile to
# optimize both build time and intermediate image size
compiler: ghc-9.10.3

packages:
  - ghidra-haskell
  - blaze
  - flint
  - binary-analysis

extra-deps:
  - lmdb-0.2.5
  - git: https://github.com/kudu-dynamics/inline-java
    commit : 8915275dae15ddd280bf45e891ccb2b3d11522ae
    subdirs:
      - jni
      - jvm
  - git: https://github.com/kudu-dynamics/selda.git
    commit : ecb3321f9cca116f658590f35a5e85fa0c6dd929
    subdirs:
      - selda
      - selda-sqlite

# Uncomment for macOS with Homebrew:
# extra-lib-dirs:
#   - /opt/homebrew/Cellar/openjdk@21/21.0.9/libexec/openjdk.jdk/Contents/Home/lib/server
#   - /opt/homebrew/Cellar/lmdb/0.9.35/lib
# extra-include-dirs:
#   - /opt/homebrew/Cellar/openjdk@21/21.0.9/libexec/openjdk.jdk/Contents/Home/include
#   - /opt/homebrew/Cellar/openjdk@21/21.0.9/libexec/openjdk.jdk/Contents/Home/include/darwin
#   - /opt/homebrew/Cellar/lmdb/0.9.35/include

rebuild-ghc-options: true
ghc-options:
  "$locals": -j -O0
  "prettyprinter": -Wno-deprecations
