resolver: lts-20.0
compiler: ghc-9.2.5

packages:
  - binaryninja-haskell
  - binaryninja-haskell/binja-header-cleaner
  - ghidra-haskell
  - blaze
  - flint

extra-deps:
  - git: https://github.com/kudu-dynamics/binary-analysis
    commit: 5a617fd1cd8314fbf06a514029c20ea1293d9ecd
  - git: https://github.com/kudu-dynamics/inline-java.git
    commit: 061fd73d661698c0b0ac3902c9832c9b499a661c
    subdirs:
      - jni
      - jvm
  - git: https://github.com/tweag/distributed-closure
    commit: 0eaace06ad1e9d80d13287b4e3b1e03f314082ed
  - language-c-0.9.2

rebuild-ghc-options: true
