resolver: lts-20.0
compiler: ghc-9.2.5

packages:
  - .

extra-deps:
  - ../binary-analysis
  - git: https://github.com/kudu-dynamics/inline-java.git
    commit: 4ce11a58b83e583426c973c403d7eb09759479e3
    subdirs:
      - jni
      - jvm
  - git: https://github.com/tweag/distributed-closure
    commit: 0eaace06ad1e9d80d13287b4e3b1e03f314082ed

rebuild-ghc-options: true
