resolver: lts-20.0
# Always keep `compiler` explicit because it's used by the Dockerfile to
# optimize both build time and intermediate image size
compiler: ghc-9.2.5

packages:
  - binaryninja-haskell
  - binaryninja-haskell/binja-header-cleaner
  - ghidra-haskell
  - blaze
  - flint

extra-deps:
  - git: https://github.com/kudu-dynamics/binary-analysis
    commit: 5a617fd1cd8314fbf06a514029c20ea1293d9ecd
  - git: https://github.com/kudu-dynamics/inline-java.git
    commit: 9de6cfa65b8d5d692bf7f5de1e4f1b853f2bbef1
    subdirs:
      - jni
      - jvm
  - git: https://github.com/tweag/distributed-closure
    commit: 0eaace06ad1e9d80d13287b4e3b1e03f314082ed
  - language-c-0.9.2

rebuild-ghc-options: true
ghc-options:
  "$locals": -j
