resolver: nightly-2022-04-28
compiler: ghc-9.2.2

packages:
  - .
  - binja-header-cleaner

extra-deps:
  - ../binary-analysis
  - git: https://github.com/protolude/protolude
    commit: 3e249724fd0ead27370c8c297b1ecd38f92cbd5b
  - envy-2.1.0.0@sha256:b58b12d9b61a4e07562e7718f28a864178cfc4bb4c24a45c68b5e46cfd9b39be,1772

allow-newer: true
