resolver: lts-24.33
# Always keep `compiler` explicit because it's used by the Dockerfile to
# optimize both build time and intermediate image size
compiler: ghc-9.10.3

packages:
  - .

extra-deps:
  - ../binary-analysis
  - git: https://github.com/kudu-dynamics/inline-java
    commit : 8915275dae15ddd280bf45e891ccb2b3d11522ae
    subdirs:
      - jni
      - jvm

rebuild-ghc-options: true
ghc-options:
  "$locals": -j -O0
  "prettyprinter": -Wno-deprecations
