name:                flint
version:             0.1.0.0
license:             BSD-2-Clause
author:
  - Matt (drone) Revelle <drone@bitrit.es>
  - Matt Parker <mp@kududyn.com>
  - Kevin Orr <kevino@kududyn.com>
maintainer:
  - Matt Parker <mp@kududyn.com>
  - Kevin Orr <kevino@kududyn.com>
  - Matt (drone) Revelle <drone@bitrit.es>
copyright:           "2023 Kudu Dynamics"
synopsis:            An analysis tool that aids in finding bugs.
category:            Program Analysis, Binary Analysis
description:         Please see the README.

extra-source-files:
- README.md
- ChangeLog.md


dependencies:
  - aeson
  - aeson-pretty
  - algebraic-graphs
  - async
  - base >=4.7 && <5
  - bimap
  - binary-analysis
  - blaze
  - bv
  - bytestring
  - casing
  - constraints
  - containers
  - data-binary-ieee754
  - directory
  - dlist
  - envy
  - extra
  - generic-lens
  - generics-sop
  - ghidra
  - hashable
  - lens
  - list-t
  - megaparsec
  - mtl
  - newtype
  - parser-combinators
  - pretty-simple
  - random
  - raw-strings-qq
  - recursion-schemes
  - regex-tdfa
  - relude
  - selda
  - selda-sqlite
  - sbv
  - stm
  - string-conversions
  - template-haskell
  - text
  - time
  - transformers
  - unordered-containers
  - uuid >=1.3.14
  - vector

language: GHC2021

default-extensions:
  - AllowAmbiguousTypes
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - DuplicateRecordFields
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedLabels
  - OverloadedStrings
  - TypeFamilies
  - ViewPatterns

library:
  ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wpartial-fields
  - -Wmissing-home-modules
  source-dirs:
  - src
  exposed-modules:
  - Flint.Prelude
  - Flint.Analysis
  - Flint.Analysis.Path.Matcher
  - Flint.Analysis.Path.Matcher.Patterns
  - Flint.Analysis.Path.Matcher.Stub
  - Flint.Analysis.Uefi
  - Flint.App
  - Flint.Cfg
  - Flint.Cfg.Path
  - Flint.Cfg.Store
  - Flint.Graph
  - Flint.Query
  - Flint.Types.Analysis
  - Flint.Types.CachedCalc
  - Flint.Types.Cfg.Store
  - Flint.Types.Query
  - Flint.Util

executables:
  flint:
    main: Main.hs
    source-dirs:  app/flint
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint
    - optparse-applicative
  gen_flint_db:
    main: Main.hs
    source-dirs:  app/gen_flint_db
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint
    - unix
    - optparse-applicative
  routes:
    main: Main.hs
    source-dirs:  app/routes
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint
    - optparse-applicative
  binaryToGhidra:
    main: Main.hs
    source-dirs:  app/binaryToGhidra
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint
    - optparse-applicative
  ev1smm:
    main: Main.hs
    source-dirs: demo/ev1smm
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint
  divelogger:
    main: Main.hs
    source-dirs: demo/Dive_Logger
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint
  kernel:
    main: Main.hs
    source-dirs: demo/Kernel
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint
  demo1-demo:
    main: Main.hs
    source-dirs: demo/Demo1
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint
    
tests:
  flint-tests:
    main: Main.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flint
    - temporary
    - hspec
    build-tools:
      - hspec-discover
