resolver: lts-22.11
# Always keep `compiler` explicit because it's used by the Dockerfile to
# optimize both build time and intermediate image size
compiler: ghc-9.6.4

packages:
  - .

extra-deps:
  - ../blaze
  - ../binaryninja-haskell
  - ../binaryninja-haskell/binja-header-cleaner
  - ../ghidra-haskell
  - git: https://github.com/kudu-dynamics/binary-analysis
    commit: 421057ba848999f0b1ffec303eb6936e18e673cd
  - git: https://github.com/kudu-dynamics/inline-java.git
    commit: 9de6cfa65b8d5d692bf7f5de1e4f1b853f2bbef1
    subdirs:
      - jni
      - jvm
  - git: https://github.com/kudu-dynamics/selda.git
    commit : efde67c131deea943e1d76e26449aa8da46c2d01
    subdirs:
      - selda
      - selda-sqlite
      
rebuild-ghc-options: true
ghc-options:
  "$locals": -j -O0
  "prettyprinter": -Wno-deprecations
