resolver: lts-20.0
compiler: ghc-9.2.5

packages:
  - .

extra-deps:
  - ../blaze
  - ../binary-analysis
  - ../binaryninja-haskell
  - ../ghidra-haskell
  - git: https://github.com/kudu-dynamics/inline-java.git
    commit: 47d7e8c609847804676f7bdcaa3c2d45a59ba483
    subdirs:
      - jni
      - jvm
  - git: https://github.com/tweag/distributed-closure
    commit: 0eaace06ad1e9d80d13287b4e3b1e03f314082ed
  - language-c-0.9.2

rebuild-ghc-options: true
