resolver: lts-24.33
# Always keep `compiler` explicit because it's used by the Dockerfile to
# optimize both build time and intermediate image size
compiler: ghc-9.10.3

packages:
  - .

extra-deps:
  - git: https://github.com/drshade/haskell-mcp-server.git
    commit: 7991756933ae5e39ad480b0be830beb855cb8768
  - ../binary-analysis
  - ../blaze
  - ../ghidra-haskell
  - git: https://github.com/kudu-dynamics/inline-java
    commit : 8915275dae15ddd280bf45e891ccb2b3d11522ae
    subdirs:
      - jni
      - jvm
  - git: https://github.com/kudu-dynamics/selda.git
    commit : ecb3321f9cca116f658590f35a5e85fa0c6dd929
    subdirs:
      - selda
      - selda-sqlite

rebuild-ghc-options: true
ghc-options:
  "$locals": -j -O3
  "prettyprinter": -Wno-deprecations
