/* Generated by gpt o3-mini-high */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* A card structure, nested inside Account */
typedef struct Card {
    char card_number[20];
    int pin;
} Card;

/* A transaction history structure */
typedef struct TransactionHistory {
    char *log;  // dynamically allocated log buffer
    // (Could include additional fields here)
} TransactionHistory;

/* The main account structure, which contains nested structs */
typedef struct Account {
    char username[32];
    double balance;
    Card card;
    TransactionHistory *history;
    int locked;
} Account;

/* Initialize an account, allocating nested history memory */
void init_account(Account *acc, const char *username, const char *card_number, int pin, double initial_balance) {
    strncpy(acc->username, username, sizeof(acc->username) - 1);
    acc->username[sizeof(acc->username) - 1] = '\0';
    acc->balance = initial_balance;
    
    strncpy(acc->card.card_number, card_number, sizeof(acc->card.card_number) - 1);
    acc->card.card_number[sizeof(acc->card.card_number) - 1] = '\0';
    acc->card.pin = pin;
    
    acc->locked = 0;
    
    /* Allocate transaction history */
    acc->history = malloc(sizeof(TransactionHistory));
    if (acc->history) {
        acc->history->log = malloc(256);  // allocate 256 bytes for the log
        if (acc->history->log) {
            strcpy(acc->history->log, "Account created.\n");
        }
    }
}

/* Deposit funds and update the transaction history */
void deposit(Account *acc, double amount) {
    if (acc->locked) {
        printf("Account is locked.\n");
        return;
    }
    acc->balance += amount;
    printf("Deposited $%.2f. New balance: $%.2f\n", amount, acc->balance);
    
    if (acc->history && acc->history->log) {
        strncat(acc->history->log, "Deposit made.\n", 256 - strlen(acc->history->log) - 1);
    }
}

/* Withdraw funds and update the transaction history */
void withdraw(Account *acc, double amount) {
    if (acc->locked) {
        printf("Account is locked.\n");
        return;
    }
    if (acc->balance < amount) {
        printf("Insufficient funds.\n");
        return;
    }
    acc->balance -= amount;
    printf("Withdrew $%.2f. New balance: $%.2f\n", amount, acc->balance);
    
    if (acc->history && acc->history->log) {
        strncat(acc->history->log, "Withdrawal made.\n", 256 - strlen(acc->history->log) - 1);
    }
}

/*
 * Vulnerable function: prints a receipt using a user-supplied format string.
 * If the user controls the format, they can trigger a format string vulnerability.
 */
void print_receipt(Account *acc, char *user_format) {
    printf("Receipt for account: %s\n", acc->username);
    /* POTENTIAL FLAW: user_format is used directly as a format string */
    printf(user_format);
    printf("\nBalance: $%.2f\n", acc->balance);
}

/*
 * Two helper functions that each free the same pointer.
 * They do not null out the pointer after freeing.
 * Calling both in sequence can lead to a double free.
 */
void free_history_option1(Account *acc) {
    if (acc->history && acc->history->log) {
        free(acc->history->log);
        /* Vulnerability: pointer not set to NULL */
        printf("free_history_option1: Freed transaction log.\n");
    }
}

void free_history_option2(Account *acc) {
    if (acc->history && acc->history->log) {
        free(acc->history->log);
        printf("free_history_option2: Freed transaction log.\n");
    }
}

/* Intermediate functions that may trigger one of the free operations */
void intermediate_cleanup1(Account *acc, int trigger) {
    if (trigger) {
        free_history_option1(acc);
    }
}

void intermediate_cleanup2(Account *acc, int trigger) {
    if (trigger) {
        free_history_option2(acc);
    }
}

/*
 * This function simulates a transaction-processing chain.
 * Depending on the chosen option, it performs deposits, withdrawals,
 * prints a receipt (with a format string vulnerability), or
 * triggers a double free through chained cleanup functions.
 */
void process_transaction(Account *acc, int option, char *input) {
    switch (option) {
        case 1:
            deposit(acc, atof(input));
            break;
        case 2:
            withdraw(acc, atof(input));
            break;
        case 3:
            /* Pass user input directly to print_receipt (vulnerability!) */
            print_receipt(acc, input);
            break;
        case 4:
            /* Simulate potential double free: two cleanup functions are called */
            intermediate_cleanup1(acc, 1);
            intermediate_cleanup2(acc, 1);
            break;
        default:
            printf("Unknown transaction option.\n");
            break;
    }
}

/* A simple event loop simulating an ATM machine interface */
void atm_event_loop(Account *acc) {
    char choice[16];
    char buffer[256];
    int option;
    
    while (1) {
        printf("\n===== ATM Machine Interface =====\n");
        printf("1. Deposit\n");
        printf("2. Withdraw\n");
        printf("3. Print Receipt\n");
        printf("4. Cleanup Transaction History (unsafe)\n");
        printf("5. Exit\n");
        printf("Enter option: ");
        if (!fgets(choice, sizeof(choice), stdin))
            break;
        option = atoi(choice);
        if (option == 5)
            break;
        printf("Enter amount/message/input: ");
        if (!fgets(buffer, sizeof(buffer), stdin))
            break;
        buffer[strcspn(buffer, "\n")] = '\0';  // remove newline
        process_transaction(acc, option, buffer);
    }
}

/* Main function */
int main(int argc, char *argv[]) {
    Account user_account;
    init_account(&user_account, "BillyBigDog", "1234567890123456", 1234, 1000.0);
    atm_event_loop(&user_account);
    
    /* Cleanup any remaining allocated memory */
    if (user_account.history) {
        if (user_account.history->log)
            free(user_account.history->log);
        free(user_account.history);
    }
    return 0;
}
