name:                binaryninja
version:             0.1.0
license:             BSD-2-Clause
author:
  - Matt (drone) Revelle <drone@kududyn.com>
  - Matt Parker <mp@kududyn.com>
  - Kevin Orr <kevino@kududyn.com>
maintainer:
  - Matt (drone) Revelle <drone@kududyn.com>
  - Matt Parker <mp@kududyn.com>
  - Kevin Orr <kevino@kududyn.com>
copyright:           "2021 Kudu Dynamics"
synopsis:            Haskell bindings for Binary Ninja.
category:            Bindings, Binary Analysis
description:         Please see the README.

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
  - attoparsec
  - base
  - binary-analysis
  - bytestring
  - casing
  - containers
  - cryptonite
  - data-binary-ieee754
  - directory
  - envy
  - errors
  - extra
  - language-c
  - lens
  - mtl
  - newtype
  - pretty-simple
  - protolude
  - raw-strings-qq
  - stm
  - template-haskell >= 2.18.0.0
  - text
  - transformers
  - unordered-containers

language: GHC2021

default-extensions:
  - AllowAmbiguousTypes
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - DuplicateRecordFields
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedLabels
  - OverloadedStrings
  - TypeFamilies


library:
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  extra-libraries: binaryninjacore
  source-dirs:
    - src
  exposed-modules:
  - Binja.Analysis
  - Binja.Architecture
  - Binja.Core
  - Binja.View
  - Binja.Function
  - Binja.BasicBlock
  - Binja.MLIL
  - Binja.Reference
  - Binja.TypeLibrary
  - Binja.Variable
  - Binja.Prelude
  - Binja.C.Enums
  - Binja.Types.MLIL.Op.NopOp
  - Binja.Types.MLIL.Op.SetVarOp
  - Binja.Types.MLIL.Op.SetVarFieldOp
  - Binja.Types.MLIL.Op.SetVarSplitOp
  - Binja.Types.MLIL.Op.LoadOp
  - Binja.Types.MLIL.Op.LoadStructOp
  - Binja.Types.MLIL.Op.StoreOp
  - Binja.Types.MLIL.Op.StoreStructOp
  - Binja.Types.MLIL.Op.VarOp
  - Binja.Types.MLIL.Op.VarFieldOp
  - Binja.Types.MLIL.Op.VarSplitOp
  - Binja.Types.MLIL.Op.AddressOfOp
  - Binja.Types.MLIL.Op.AddressOfFieldOp
  - Binja.Types.MLIL.Op.ConstOp
  - Binja.Types.MLIL.Op.ConstDataOp
  - Binja.Types.MLIL.Op.ConstPtrOp
  - Binja.Types.MLIL.Op.ExternPtrOp
  - Binja.Types.MLIL.Op.FloatConstOp
  - Binja.Types.MLIL.Op.ImportOp
  - Binja.Types.MLIL.Op.AddOp
  - Binja.Types.MLIL.Op.AdcOp
  - Binja.Types.MLIL.Op.SubOp
  - Binja.Types.MLIL.Op.SbbOp
  - Binja.Types.MLIL.Op.AndOp
  - Binja.Types.MLIL.Op.OrOp
  - Binja.Types.MLIL.Op.XorOp
  - Binja.Types.MLIL.Op.LslOp
  - Binja.Types.MLIL.Op.LsrOp
  - Binja.Types.MLIL.Op.AsrOp
  - Binja.Types.MLIL.Op.RolOp
  - Binja.Types.MLIL.Op.RlcOp
  - Binja.Types.MLIL.Op.RorOp
  - Binja.Types.MLIL.Op.RrcOp
  - Binja.Types.MLIL.Op.MulOp
  - Binja.Types.MLIL.Op.MuluDpOp
  - Binja.Types.MLIL.Op.MulsDpOp
  - Binja.Types.MLIL.Op.DivuOp
  - Binja.Types.MLIL.Op.DivuDpOp
  - Binja.Types.MLIL.Op.DivsOp
  - Binja.Types.MLIL.Op.DivsDpOp
  - Binja.Types.MLIL.Op.ModuOp
  - Binja.Types.MLIL.Op.ModuDpOp
  - Binja.Types.MLIL.Op.ModsOp
  - Binja.Types.MLIL.Op.ModsDpOp
  - Binja.Types.MLIL.Op.NegOp
  - Binja.Types.MLIL.Op.NotOp
  - Binja.Types.MLIL.Op.SxOp
  - Binja.Types.MLIL.Op.ZxOp
  - Binja.Types.MLIL.Op.LowPartOp
  - Binja.Types.MLIL.Op.JumpOp
  - Binja.Types.MLIL.Op.JumpToOp
  - Binja.Types.MLIL.Op.RetHintOp
  - Binja.Types.MLIL.Op.CallOp
  - Binja.Types.MLIL.Op.CallUntypedOp
  - Binja.Types.MLIL.Op.CallOutputOp
  - Binja.Types.MLIL.Op.CallParamOp
  - Binja.Types.MLIL.Op.RetOp
  - Binja.Types.MLIL.Op.NoretOp
  - Binja.Types.MLIL.Op.IfOp
  - Binja.Types.MLIL.Op.GotoOp
  - Binja.Types.MLIL.Op.CmpEOp
  - Binja.Types.MLIL.Op.CmpNeOp
  - Binja.Types.MLIL.Op.CmpSltOp
  - Binja.Types.MLIL.Op.CmpUltOp
  - Binja.Types.MLIL.Op.CmpSleOp
  - Binja.Types.MLIL.Op.CmpUleOp
  - Binja.Types.MLIL.Op.CmpSgeOp
  - Binja.Types.MLIL.Op.CmpUgeOp
  - Binja.Types.MLIL.Op.CmpSgtOp
  - Binja.Types.MLIL.Op.CmpUgtOp
  - Binja.Types.MLIL.Op.TestBitOp
  - Binja.Types.MLIL.Op.BoolToIntOp
  - Binja.Types.MLIL.Op.AddOverflowOp
  - Binja.Types.MLIL.Op.SyscallOp
  - Binja.Types.MLIL.Op.SyscallUntypedOp
  - Binja.Types.MLIL.Op.TailcallOp
  - Binja.Types.MLIL.Op.TailcallUntypedOp
  - Binja.Types.MLIL.Op.BpOp
  - Binja.Types.MLIL.Op.TrapOp
  - Binja.Types.MLIL.Op.IntrinsicOp
  - Binja.Types.MLIL.Op.IntrinsicSSAOp
  - Binja.Types.MLIL.Op.FreeVarSlotOp
  - Binja.Types.MLIL.Op.FreeVarSlotSSAOp
  - Binja.Types.MLIL.Op.UndefOp
  - Binja.Types.MLIL.Op.UnimplOp
  - Binja.Types.MLIL.Op.UnimplMemOp
  - Binja.Types.MLIL.Op.FaddOp
  - Binja.Types.MLIL.Op.FsubOp
  - Binja.Types.MLIL.Op.FmulOp
  - Binja.Types.MLIL.Op.FdivOp
  - Binja.Types.MLIL.Op.FsqrtOp
  - Binja.Types.MLIL.Op.FnegOp
  - Binja.Types.MLIL.Op.FabsOp
  - Binja.Types.MLIL.Op.FloatToIntOp
  - Binja.Types.MLIL.Op.IntToFloatOp
  - Binja.Types.MLIL.Op.FloatConvOp
  - Binja.Types.MLIL.Op.RoundToIntOp
  - Binja.Types.MLIL.Op.FloorOp
  - Binja.Types.MLIL.Op.CeilOp
  - Binja.Types.MLIL.Op.FtruncOp
  - Binja.Types.MLIL.Op.FcmpEOp
  - Binja.Types.MLIL.Op.FcmpNeOp
  - Binja.Types.MLIL.Op.FcmpLtOp
  - Binja.Types.MLIL.Op.FcmpLeOp
  - Binja.Types.MLIL.Op.FcmpGeOp
  - Binja.Types.MLIL.Op.FcmpGtOp
  - Binja.Types.MLIL.Op.FcmpOOp
  - Binja.Types.MLIL.Op.FcmpUoOp
  - Binja.Types.MLIL.Op.SetVarSSAOp
  - Binja.Types.MLIL.Op.SetVarSSAFieldOp
  - Binja.Types.MLIL.Op.SetVarSplitSSAOp
  - Binja.Types.MLIL.Op.SetVarAliasedOp
  - Binja.Types.MLIL.Op.SetVarAliasedFieldOp
  - Binja.Types.MLIL.Op.VarSSAOp
  - Binja.Types.MLIL.Op.VarSSAFieldOp
  - Binja.Types.MLIL.Op.VarAliasedOp
  - Binja.Types.MLIL.Op.VarAliasedFieldOp
  - Binja.Types.MLIL.Op.VarSplitSSAOp
  - Binja.Types.MLIL.Op.CallSSAOp
  - Binja.Types.MLIL.Op.CallUntypedSSAOp
  - Binja.Types.MLIL.Op.SyscallSSAOp
  - Binja.Types.MLIL.Op.SyscallUntypedSSAOp
  - Binja.Types.MLIL.Op.TailcallSSAOp
  - Binja.Types.MLIL.Op.TailcallUntypedSSAOp
  - Binja.Types.MLIL.Op.CallOutputSSAOp
  - Binja.Types.MLIL.Op.CallParamSSAOp
  - Binja.Types.MLIL.Op.LoadSSAOp
  - Binja.Types.MLIL.Op.LoadStructSSAOp
  - Binja.Types.MLIL.Op.StoreSSAOp
  - Binja.Types.MLIL.Op.StoreStructSSAOp
  - Binja.Types.MLIL.Op.VarPhiOp
  - Binja.Types.MLIL.Op.MemPhiOp
  - Binja.Types.TypeLibrary

build-tools:
  - c2hs

include-dirs:
  - "src"
  - "res"

tests:
  binja-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    extra-libraries: binaryninjacore
    dependencies:
    - containers
    - binaryninja
    - hspec
    - text
