module Main (main) where

import Flint.Prelude hiding ((.=))

import Flint.Types.Analysis.Path.Matcher.Primitives (PrimSpec(PrimSpec, name, vars, locations))
import Flint.Types.Symbol

import qualified Data.HashSet as HashSet
import qualified Data.Text as Text
import qualified Data.Text.IO as TextIO
import Options.Applicative hiding (info)
import qualified Options.Applicative as OA
import Toml (TomlCodec, (.=))
import qualified Toml

data Options = Options
  { inputSpecFile :: Maybe FilePath
  , outputModule :: Maybe FilePath
  }
  deriving (Eq, Ord, Read, Show, Generic)

parseInputSpecFile :: Parser FilePath
parseInputSpecFile = option str
  ( long "inputSpecFile"
    <> short 'i'
    <> metavar "INPUT_SPEC_FILE"
    <> help "file containing the primitive specs (default res/primspec.yaml)"
  )

parseOutputModule :: Parser FilePath
parseOutputModule = option str
  ( long "outputModule"
    <> short 'o'
    <> metavar "OUTPUT_MODULE"
    <> help "output Haskell module path"
  )

optionsParser :: Parser Options
optionsParser = Options
  <$> optional parseInputSpecFile
  <*> optional parseOutputModule

defaultInputSpecLocation :: FilePath
defaultInputSpecLocation = "res/primspec.toml"

defaultOutputModule :: FilePath
defaultOutputModule = "src/Flint/Analysis/Path/Matcher/Primitives/Library/PrimSpec.hs"

symbolBiMap :: Toml.TomlBiMap (Symbol a) Toml.AnyValue
symbolBiMap = Toml.mkAnyValueBiMap (fmap Symbol . Toml.matchText) (Toml.Text . unSymbol)

primSpecCodec :: TomlCodec PrimSpec
primSpecCodec = PrimSpec
  <$> Toml.text                       "name"      .= name
  <*> Toml.arrayHashSetOf symbolBiMap "vars"      .= vars
  <*> Toml.arrayHashSetOf symbolBiMap "locations" .= locations

primSpecListCodec :: TomlCodec [PrimSpec]
primSpecListCodec = Toml.list primSpecCodec "prim"

outputModuleHeader :: Text
outputModuleHeader = Text.unlines
  [ "module Flint.Analysis.Path.Matcher.Primitives.Library.PrimSpec where"
  , ""
  , "import Flint.Types.Analysis.Path.Matcher.Primitives"
  , ""
  , "import Data.HashSet (fromList)"
  , ""
  , "-- DO NOT EDIT THIS FILE"
  , "-- This module is auotgenerated! Use gen_primspec to generate"
  , ""
  , ""
  ]

lowerFirst :: Text -> Text
lowerFirst t = case Text.uncons t of
  Just (c, rest) -> Text.cons (toLower c) rest
  Nothing        -> t  -- empty string, leave it alone

quote :: Text -> Text
quote t = "\"" <> t <> "\""

showPrimSpecDef :: PrimSpec -> Text
showPrimSpecDef x = Text.unlines
  [ defName <> " :: PrimSpec"
  , defName <> " = PrimSpec"
  , "  { name = " <> quote (x ^. #name)
  , "  , vars = fromList " <> symbolList (x ^. #vars)
  , "  , locations = fromList " <> symbolList (x ^. #locations)
  , "  }"
  ]
  where
    defName = lowerFirst $ x ^. #name <> "Spec"
    symbolList :: forall a. HashSet (Symbol a) -> Text
    symbolList syms
      = "["
        <> Text.intercalate ", " (fmap (quote . unSymbol) . HashSet.toList $ syms)
        <> "]"

showPrimSpecModule :: [PrimSpec] -> Text
showPrimSpecModule prims =
  outputModuleHeader
  <> Text.intercalate "\n" (showPrimSpecDef <$> prims)

main :: IO ()
main = do
  opts <- execParser optsParser
  inputSpecFile <- case opts ^. #inputSpecFile of
    Nothing -> do
      putText $ "Using default input spec file: " <> cs defaultInputSpecLocation
      return defaultInputSpecLocation
    Just s -> return s
  let outputModule = fromMaybe defaultOutputModule $ opts ^. #outputModule
  rawToml <- TextIO.readFile inputSpecFile
  case Toml.decode primSpecListCodec rawToml of
    Left err -> error . show $ err
    Right prims -> do
      putText $ "Wrote " <> show (length prims) <> " primspecs to " <> cs outputModule
      TextIO.writeFile outputModule $ showPrimSpecModule prims
  return ()
  where
    optsParser = OA.info (optionsParser <**> helper)
      ( fullDesc
        <> progDesc "Creates the PrimSpec.hs Haskell module from a primspec.yaml file"
        <> header "gen_primspecn" )
