name: build
on:
  push:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: docker
        uses: docker/build-push-action@v7
        with:
          outputs: type=cacheonly
          tags: myimage:pipeline
          target: just-deps
      - name: hlint
        run: just hlint --color=always
  build:
    runs-on: ubuntu-24.04
    steps:
      - run: echo build-$GITHUB_RUN_ID
#    outputs:
#
#    steps:
#      
  test:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - run: echo "test"
#on:
#  pull_request:
#    branches:
#      - main
