name: build
on:
  push:
  pull_request:
    branches:
      - main
env:
  HASKELL_OPTIM: "-O0"
  DOCKER_RUN_ID: 24477541928 # update this every run of docker.yml
permissions:
  contents: read
jobs:
  warnings:
    runs-on: ubuntu-24.04
    steps:
      - name: download # suggest rerunning docker.yml if this fails
        uses: actions/download-artifact@v8
        with:
          name: just-deps
          run-id: $DOCKER_RUN_ID
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          path: /tmp
      - name: docker
        id: docker
        run: |
          docker load --input /tmp/just-deps.tar
          docker run just-deps:latest ls -l
      - name: warnings
        run: |
          docker run just-deps:latest stack clean
          docker run --rm just-deps:latest stack --color always build --test --no-run-tests --pedantic --fast
      - name: suggest
        if: ${{ failure() && steps.docker.conclusion == 'failure' }}
        run: |
          echo "This probably failed because there is an " > $GITHUB_STEP_SUMMARY
          echo "issue with the cached docker image. Rerun " >> $GITHUB_STEP_SUMMARY
          echo "`image` workflow and copy the run ID into " >> $GITHUB_STEP_SUMMARY
          echo "`.github/workflows/build.yml` as the " >> $GITHUB_STEP_SUMMARY
          echo "\$DOCKER_RUN_ID env variable." >> $GITHUB_STEP_SUMMARY
  hlint:
    runs-on: ubuntu-24.04
    steps:
      - name: download
        uses: actions/download-artifact@v8
        with:
          name: haskell
          run-id: $DOCKER_RUN_ID
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          path: /tmp
      - name: hlint
        run: |
          docker load --input /tmp/haskell.tar
          docker run haskell:latest ls -l
          docker run --rm haskell:latest just hlint --color=always
  build:
    runs-on: ubuntu-24.04
#    needs: docker # technically not true
    steps:
#      - name: checkout
#        uses: actions/checkout@v6
      - name: setup
        uses: docker/setup-buildx-action@v4
      - name: builder # look into cache-to, cache-from with artifacts
        uses: docker/build-push-action@v7
        with:
          target: builder
          build-args: OPTIM=$HASKELL_OPTIM
          tags: builder:latest
          outputs: type=docker,dest=/tmp/builder.tar
      - name: test
        run: |
          docker load --input /tmp/builder.tar
          docker run builder:latest ls -l
          docker run builder:latest ls -l /out
          docker run builder:latest file /out/run-tests
          dockre run builder:latest uname -a
          docker run --rm builder:latest /out/run-tests --color
#      - name: deliver
#        uses: docker/build-push-action@v7
#        with:
#          target: deliver
#  test:
#    needs: build
#    runs-on: ubuntu-24.04
#    steps:
#      - run: /out/run-tests --color
