name: build
on:
  push:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
#      - name: setup # remove this step if deemed unnecessary
#        uses: docker/setup-buildx-action@v4
      - name: download # suggest rerunning docker.yml if this fails
        uses: actions/download-artifact@v8
        with:
          name: myimage
          run-id: 24422167052 # make this a variable updated every run of docker.yml
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          path: /tmp
      - name: load
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
      - name: hlint
        run: |
          docker run myimage:latest just hlint --color=always
      - name: warnings
        run: |
          docker run myimage:latest stack clean
          docker run --rm stack --color always build --test --no-run-tests --pedantic --fast
  build:
    runs-on: ubuntu-24.04
#    needs: docker # technically not true
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: builder # look into cache-to, cache-from with artifacts
        uses: docker/build-push-action@v7
        with:
          target: builder
          build-args: OPTIM="-O0" # make this an env variable
#      - name: deliver
#        uses: docker/build-push-action@v7
#        with:
#          target: deliver
  test:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - run: /out/run-tests --color
