name: validate changelog
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  validate:
    if: ${{ github.repository == 'kudu-dynamics/blaze-platform' }}
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - name: validate
        run: |
          # should use $GITHUB_BASE_REF instead of hardcoding main
          git fetch origin main --depth 1
          git diff $GITHUB_HEAD_REF origin/main -- CHANGELOG.md | grep "[[:alnum:]]"
