name: validate changelog
on:
  push: # delete this line before merge
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - name: validate
        run: |
          echo $GITHUB_HEAD_REF
          echo $GITHUB_BASE_REF
          git branch -vv
          git fetch origin $GITHUB_BASE_REF --depth 1
          git checkout origin/main
          git diff $GITHUB_HEAD_REF $GITHUB_BASE_REF -- CHANGELOG.md | grep "[[:alnum:]]"
